PAYMENT_PENDING = "pending"
PAYMENT_PAID = "paid"
PAYMENT_FAILED = "failed"

BOOKING_PENDING = "pending"
BOOKING_CONFIRMED = "confirmed"
BOOKING_CANCELLED = "cancelled"

APPOINTMENT_BOOKED = "booked"
APPOINTMENT_CANCELLED = "cancelled"
APPOINTMENT_COMPLETED = "completed"

OTP_EXPIRY_MINUTES = 5